language: cpp

# branches:
#   except:
#     - /^feature.*$/

sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "QHBCY7S3ZYOtu5zujyMnyHg74srAIfFSKJbrlBdETk2T6YStPug3Z5PuY7ahXfPyM/4w7og8KyvuGZL0YsJrNaJSpsbDETtwvKEorzLjfKyRwDV2SyTpnSLauGgZmjPZnkXzp8lQIR+cIo7of6frjxd47E8WCKCGFJKa0pUG5Bw="
  matrix:
    - BUILD=gcc
    - BUILD=clang

script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then
      case ${BUILD} in
        gcc)
          cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug . &&
          make &&
          make coveralls
          ;;
        clang)
          cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=cmake/clang.cmake . &&
          make &&
          make coveralls
          ;;
      esac ;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - cmake
    - doxygen
    - valgrind
    - libboost-dev
    - libboost-test-dev

  coverity_scan:
    project:
      name: "gatzka/cjet"
      description: "Build submitted via Travis CI"
    build_script_url: https://raw.githubusercontent.com/gatzka/cjet/coverity_scan/scripts/travis/travisci_build_coverity_scan.sh
    notification_email: stephan.gatzka@gmail.com
    build_command_prepend: "cmake ../"
    build_command: "make"
    branch_pattern: coverity_scan

